services:    
  postgres:
    image: postgres:16
    container_name: postgres
    # restart: always
    ports:
      - "3001:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      # - ./init-postgres.sql:/docker-entrypoint-initdb.d/init.sql

volumes: 
  pgdata:

# networks:
#   back-tier:
#     ipam:
#       driver: default
#       config:
#         - subnet: "172.16.238.0/24"